### ISSUE TITLE
The bot should be able to do maths with any integer

### ISSUE THREAD

**Issue by swt2public** [derari/py-twitter-bot-exercise#4]
Given a tweet "93+1",
Then the bot's answer should contain "94".

### Hints
* To split the term into operands, you can use [`myString.split('+')`](https://docs.python.org/2/library/stdtypes.html#str.split), where `myString` is a variable containing your string.
* `split` returns an array, here is a small example
  <pre>myString = "1+2"
  arguments = myString.split('+')
  print arguments[0] #(prints '1')
  print arguments[1] #(prints '2')</pre>
* To convert a  string to an integer, you can use [`int(myString)`](https://docs.python.org/2/library/functions.html#int).
        

>Failed, got exception:
```
Traceback (most recent call last):
  File "travis_test.py", line 160, in test_mathX
    response = self.reply_to(a + "+" + b)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by swt2public** [comment]
Given a tweet "38+11",
Then the bot's answer should contain "49".

### Hints
* To split the term into operands, you can use [`myString.split('+')`](https://docs.python.org/2/library/stdtypes.html#str.split), where `myString` is a variable containing your string.
* `split` returns an array, here is a small example
  <pre>myString = "1+2"
  arguments = myString.split('+')
  print arguments[0] #(prints '1')
  print arguments[1] #(prints '2')</pre>
* To convert a  string to an integer, you can use [`int(myString)`](https://docs.python.org/2/library/functions.html#int).
        

>Failed, got exception:
```
Traceback (most recent call last):
  File "travis_test.py", line 160, in test_mathX
    response = self.reply_to(str(a) + "+" + b)
TypeError: cannot concatenate 'str' and 'int' objects
```

**Comment by swt2public** [comment]
Given a tweet "88+85",
Then the bot's answer should contain "173".

### Hints
* To split the term into operands, you can use [`myString.split('+')`](https://docs.python.org/2/library/stdtypes.html#str.split), where `myString` is a variable containing your string.
* `split` returns an array, here is a small example
  <pre>myString = "1+2"
  arguments = myString.split('+')
  print arguments[0] #(prints '1')
  print arguments[1] #(prints '2')</pre>
* To convert a  string to an integer, you can use [`int(myString)`](https://docs.python.org/2/library/functions.html#int).
        

>Expected response containing "173",  
but got `None`

**Comment by swt2public** [comment]
Given a tweet "32+32",
Then the bot's answer should contain "64".

### Hints
* To split the term into operands, you can use [`myString.split('+')`](https://docs.python.org/2/library/stdtypes.html#str.split), where `myString` is a variable containing your string.
* `split` returns an array, here is a small example
  <pre>myString = "1+2"
  arguments = myString.split('+')
  print arguments[0] #(prints '1')
  print arguments[1] #(prints '2')</pre>
* To convert a  string to an integer, you can use [`int(myString)`](https://docs.python.org/2/library/functions.html#int).
        

>Expected response to contain "64",  
but got "@TestUser 456".

**Comment by swt2public** [comment]
Given a tweet "95+12",
Then the bot's answer should contain "107".

### Hints
* To split the term into operands, you can use [`myString.split('+')`](https://docs.python.org/2/library/stdtypes.html#str.split), where `myString` is a variable containing your string.
* `split` returns an array, here is a small example
  <pre>myString = "1+2"
  arguments = myString.split('+')
  print arguments[0] #(prints '1')
  print arguments[1] #(prints '2')</pre>
* To convert a  string to an integer, you can use [`int(myString)`](https://docs.python.org/2/library/functions.html#int).
        

>Expected response containing "107",  
but got `None`

**Comment by swt2public** [comment]
Given a tweet "88+22",
Then the bot's answer should contain "110".

### Hints
* To split the term into operands, you can use [`myString.split('+')`](https://docs.python.org/2/library/stdtypes.html#str.split), where `myString` is a variable containing your string.
* `split` returns an array, here is a small example
  <pre>myString = "1+2"
  arguments = myString.split('+')
  print arguments[0] #(prints '1')
  print arguments[1] #(prints '2')</pre>
* To convert a  string to an integer, you can use [`int(myString)`](https://docs.python.org/2/library/functions.html#int).
        

>Expected response containing "110",  
but got `None`

**Comment by swt2public** [comment]
Given a tweet "27+40",
Then the bot's answer should contain "67".

### Hints
* To split the term into operands, you can use [`myString.split('+')`](https://docs.python.org/2/library/stdtypes.html#str.split), where `myString` is a variable containing your string.
* `split` returns an array, here is a small example
  <pre>myString = "1+2"
  arguments = myString.split('+')
  print arguments[0] #(prints '1')
  print arguments[1] #(prints '2')</pre>
* To convert a  string to an integer, you can use [`int(myString)`](https://docs.python.org/2/library/functions.html#int).
        

>Expected response containing "67",  
but got `None`

**Comment by swt2public** [comment]
Given a tweet "18+36",
Then the bot's answer should contain "54".

### Hints
* To split the term into operands, you can use [`myString.split('+')`](https://docs.python.org/2/library/stdtypes.html#str.split), where `myString` is a variable containing your string.
* `split` returns an array, here is a small example
  <pre>myString = "1+2"
  arguments = myString.split('+')
  print arguments[0] #(prints '1')
  print arguments[1] #(prints '2')</pre>
* To convert a  string to an integer, you can use [`int(myString)`](https://docs.python.org/2/library/functions.html#int).
        

>Expected response containing "54",  
but got `None`

**Comment by swt2public** [comment]
Given a tweet "4+93",
Then the bot's answer should contain "97".

### Hints
* To split the term into operands, you can use [`myString.split('+')`](https://docs.python.org/2/library/stdtypes.html#str.split), where `myString` is a variable containing your string.
* `split` returns an array, here is a small example
  <pre>myString = "1+2"
  arguments = myString.split('+')
  print arguments[0] #(prints '1')
  print arguments[1] #(prints '2')</pre>
* To convert a  string to an integer, you can use [`int(myString)`](https://docs.python.org/2/library/functions.html#int).
        

>Expected response containing "97",  
but got `None`
